# Dockerfile for https://index.docker.io/u/azngeek/mothership/
# http://crosbymichael.com/dockerfile-best-practices-take-2.html
FROM php:5.6-apache

# Available PHP Extensions
# bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl
# json ldap mbstring mcrypt mssql mysql mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci
# pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets
# spl standard sybase_ct sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
RUN apt-cache search ^libmcrypt

RUN apt-get update && apt-get install -y \
    vim \
    libpng12-dev \
    curl \
    wget \
    zip \
    && docker-php-ext-install -j$(nproc) mysql pcntl pdo_mysql gd json

RUN yes | pecl install xdebug
COPY templates/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
#RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini

RUN pecl install imagick-beta

# Magerun
RUN wget --no-check-certificate https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar -O /usr/local/bin/magerun

# Copy the apache configuration
RUN mkdir -p /srv/local.docker/www
RUN mkdir -p /var/log/local.docker
COPY templates/project.conf /etc/apache2/sites-enabled/local-docker.conf

WORKDIR /srv/local.docker/www